name: Main Branch CI/CD

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Static Code Check & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Lint check
        run: ./gradlew lint

      - name: Unit Test
        run: ./gradlew test