name: Main Branch CI/CD

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Static Code Check & Test
    runs-on: ubuntu-18.04
    env:
      CCDROIDX_RELEASE_KEYSTORE_PASSWORD: ${{ secrets.CCDROIDX_RELEASE_KEYSTORE_PASSWORD }}
      CCDROIDX_RELEASE_KEY_ALIAS: ${{ secrets.CCDROIDX_RELEASE_KEY_ALIAS }}
      CCDROIDX_RELEASE_KEY_ALIAS_PASSWORD: ${{ secrets.CCDROIDX_RELEASE_KEY_ALIAS_PASSWORD }}
      CCDROIDX_RELEASE_KEYSTORE_PATH: release.keystore
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Stub release keystore file
        run: |
          touch release.keystore

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Lint check
        run: ./gradlew lintDebug

      - name: Unit Test
        run: ./gradlew testDebug